expensewebsite/expensewebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pyfinance.urls')),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
]

expensewebsite/pyfinance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' ),
    path('shopping/', views.shopping, name="shopping"),
    path('payment/', views.payment, name="payment"),
]

expensewebsite/user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('user_finance', views.user_finance, name='user_finance'),
    path('register_user_finance', views.register_user_finance, name='register-user-finance'),
    path('logout_user_finance', views.logout_user_finance, name='logout-user-finance')
]

expensewebsite/pyfinance/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY = (
        ("Mercado", "Mercado"),
        ("Ifood", "Ifood"),
        ("Casa", "Casa"),
        ("Carro", "Carro")
    )

class Compras(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    modal_displayed = models.BooleanField(default=False)
    category = models.CharField(max_length=20, choices=CATEGORY)
    date = models.DateField()
    value = models.FloatField()

class Month(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    month = models.CharField(max_length=20)
    value_all = models.FloatField()
    payment_number = models.FloatField(null=True, default=0)

expensewebsite/user/models.py
from django.db import models

# Create your models here.

expensewebsite/pyfinance/forms.py
from django import forms
from .models import Compras

class ComprasForm(forms.ModelForm):
    class Meta:
        model = Compras
        fields = "__all__"

        widgets = {
            'date':forms.DateInput(attrs={'type':'date'})
        }

expensewebsite/user/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]

    

expensewebsite/pyfinance/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ComprasForm
from .models import Compras, Month
from .matplot import generate_pie_chart, generate_chart_bar
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required(login_url='user_finance')
def index(request):
    user = request.user
    list_category = Compras.objects.filter(user=user)
    range_month = Month.objects.filter(user=user)
    categories = [item.category for item in list_category]
    values = [item.value for item in list_category]
    chart_data = generate_pie_chart(categories, values)
    context ={
        'list_category':list_category,
        'chart_data':chart_data,
        'range_month':range_month
    }
    return render(request, 'index.html', context)

@login_required(login_url='user_finance')
def shopping(request):
    form = ComprasForm(request.POST)
    if request.method == 'POST':
        user = request.user
        category = request.POST.get('category')
        date = request.POST.get('date')
        if request.POST.get('value') == '':
            messages.error(request, f'POR FAVOR INSIRA O CAMPO VALOR!!')
            return redirect('shopping')
        else:
            value = float(request.POST.get('value').replace(",", "."))


        data_obj = datetime.strptime(date, '%Y-%m-%d')
        month_name = data_obj.strftime('%B')

        dados_mensais, created = Month.objects.get_or_create(
            user=user,
            month = month_name,
            defaults={'value_all':value}
        )

        if not created:
            dados_mensais.value_all += value
       
        dados_mensais.save()

        existing_category = Compras.objects.filter(category=category, user=request.user).first()

        if existing_category:
            existing_category.value += value
            existing_category.save()
        else:
            Compras.objects.create(
                user=user,
                category=category,
                date=date,
                value= value
            )
        messages.success(request, "ADICIONADO COM SUCESSO!!!")
        
    return render(request, "shopping.html", {'form': form})


@login_required (login_url='user_finance')
def payment(request):
    if request.method == 'POST':
        payment_value = float(request.POST.get('number').replace(",", "."))
        last_object = Month.objects.last()

        if last_object:
            last_object.payment_number += payment_value
            if last_object.payment_number > last_object.value_all:
                messages.error(request, 'Não é possivel pagar valor maior que seu gasto do mês')
                return redirect('payment')
            last_object.save()

    user = request.user
    values = Month.objects.filter(user=user)
    categories = ["Gastos", "Pagar"]
    total = 0
    if values:
        for i in values:
            total = i.value_all
            number = i.payment_number
    else:
        messages.error(request, 'Por favor insira valores no mês que você esta para acessar "Pagamento"')
        return redirect('shopping')
    values = [total, number ]

    dif = total - number
      

    chart_data = generate_chart_bar(categories, values)
   
    context={
        'chart_data':chart_data,
        'total':total,
        'number':number,
        'dif':dif
    }
    return render(request, 'payment.html', context)

expensewebsite/user/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import auth
from django.contrib import messages

def user_finance(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Usuario não existe! Favor registre seu usuario.')
            return redirect('user_finance')
    return render(request, 'user_finance.html')

def register_user_finance(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if len(username) < 4:
            messages.error(request, "Por favor insira usuario com mais de 4 caracteres")
            return redirect('register-user-finance')
        for i in username:
            if i.isdigit():
                messages.error(request, "Nome de usuario não pode conter numeros!")
                return redirect('register-user-finance')
        if len(password) < 8:
            messages.error(request, "Favor insira senha maior que 8 digitos!")
            return redirect('register-user-finance')
        user = User.objects.create_user(
            username=username,
            password=password
            )
        print(user)

        user.save() 
        return redirect('user_finance')
    return render(request, 'register.html')

def logout_user_finance(request):
    auth.logout(request)

    return redirect('user_finance')

expensewebsite/templates/index.html
{% extends "partials/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>$ Money-Undercontrol $</title>
</head>
<body>
{% block content %}
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
              <h1 class="h2">Dashboard</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  <button class="btn btn-sm btn-outline-secondary">Share</button>
                  <button class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                  <span data-feather="calendar"></span>
                  This week
                </button>
              </div>
            </div>
            <canvas class="my-4" id="myChart" width="900" height="380"></canvas>
            <hr>
            <img src="{{ chart_data }}" alt="Gráfico de Pizza">
            <hr>
            <h2>Categorias de Gastos</h2>
            <div class="table-responsive">
              <table class="table table-bordered table-dark">
                <thead>
                  <tr>
                    <th>Categoria</th>
                    <th>Valor Total</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in list_category %}
                      <tr>
                        <td>{{item.category}}</td>
                        <td>R$:{{item.value}}</td>
                        <td><a class="btn btn-success" href="">Editar</a></td>
                      </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </main>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <!-- Icons -->
      <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
      <script>
        feather.replace()
      </script>
  
      <!-- Graphs -->
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
      <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: [{% for month in range_month %} '{{month.month}}',{% endfor %}],
            datasets: [{
              data: [{% for value in range_month %} {{ value.value_all }},{% endfor %}],
              lineTension: 0,
              backgroundColor: 'transparent',
              borderColor: '#007bff',
              borderWidth: 4,
              pointBackgroundColor: '#007bff'
            }]
          },
          options: {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: false
                }
              }]
            },
            legend: {
              display: false,
            }
          }
        });
    </script>
{% endblock %}
</body>
</html>

expensewebsite/templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <title>Money-Undercontrol</title>
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    
</head>

<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 navbar-expand-md">
        <div class="container">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url "index" %}">Money UnderControl</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "logout-user-finance" %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url "index" %}">
                                <span data-feather="home"></span>
                                Dashboard <span class="sr-only"></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "shopping" %}">
                                <span data-feather="shopping-cart"></span>
                                Compras
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "payment" %}">
                                <span data-feather="dollar-sign"></span>
                                Pagamentos
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
        
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                {% block content %}
                  
                {% endblock %}
            </main>
        </div>
    </div>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
      <script>
        feather.replace()
      </script>

</body>
</html>
{% comment %} 
https://feathericons.com/
{% endcomment %}

expensewebsite/templates/payment.html
{% extends "partials/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>Payment</title>
</head>
<body>
{% block content %} 
    <img style="width:500px;position:absolute; left:200px" src="{{ chart_data }}" alt="Gráfico de Pizza">
    <div class="col-md-4 mb-1" style="left:650px; top:50px">
        <form method="post" action="{% url "payment" %}">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <label for="value" name="number">Valor do Pagamento:</label>
            <input type="text" class="form-control" id="value" name="number" placeholder="Exemplo:100">
            <br>   
            <button class="btn btn-success" type="submit">Pagar</button>
        </form>
    </div>
    {% if total == number %}
        <div class="col-md-4 mb-1" style="top:400px; right: -300px; text-align:center">
            <i class="success-icon">&#10004;</i>
            <h1>Contas em Dia!</h1>
            <p>Todas as contas foram devidamente pagas e estão em dia. Obrigado pela sua pontualidade!</p>
        </div>
    {% elif total > number %}
        <div class="col-md-4 mb-1" style="top:400px; right: -300px; text-align:center">
            <i class="warning-icon">&#9888;</i>
            <h1>Contas Atrasadas!</h1>
            <h1>R$:(-{{dif|floatformat}})</h1>
            <p>Atenção! Algumas contas estão atrasadas. Por favor, regularize a situação o mais rápido possível.</p>
        </div>
    {% else %}
    <div class="col-md-4 mb-1" style="top:400px; right: -300px; text-align:center">
        <i class="warning-icon">&#9888;</i>
        <h1>Seja bem vindo ao gerenciamento de gastos!</h1>
        <p></p>
    </div>
    {% endif %}

    
{% endblock  %}
</body>
</html>

expensewebsite/templates/register.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <title>Finance.Py</title>
    <link href="{% static 'css/bootstrap.min.user.css' %}" rel="stylesheet">
    <link href="{% static "css/signin.css" %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form method = "post"class="form-signin">
      {% csrf_token %}
      <div class="container">
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <img class="mb-4" src="{% static "img/money.png" %}" alt="" width="110" height="90">
      <h1 class="h3 mb-3 font-weight-normal">Login</h1>


      <label for="username" class="sr-only">Username</label>
      <input name="username" id="username" type="text" class="form-control" placeholder="Username">

      <br>

      <label for="password" class="sr-only">Password</label>
      <input name="password" id="password" type="password" class="form-control" placeholder="Password" required>

      <br>

      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Registrar usuario</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2022-2023</p>
    </form>
  </body>
</html>

expensewebsite/templates/sale.html
{% extends "partials/base.html" %}

expensewebsite/templates/shopping.html
{% extends "partials/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <div class="container mt-5">
        <form method="post" action="{% url 'shopping' %}">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    <label for="id_category">Categoria</label>
                    <select class="custom-select" id="id_category" name="category" required>
                        <option selected disabled value="">Selecione</option>
                        {% for choice in form.category.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="id_date">Data da compra</label>
                    <input type="date" class="form-control" id="id_date" name="date" required>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="value">Valor da compra</label>
                    <input type="text" class="form-control" id="value" name="value">
                </div>
            </div>
            <button class="btn btn-primary" type="submit">Cadastrar Compra</button>
        </form>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% endblock %}
</body>
</html>

expensewebsite/templates/user_finance.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <title>Money-Undercontrol</title>
    <link href="{% static 'css/bootstrap.min.user.css' %}" rel="stylesheet">
    <link href="{% static "css/signin.css" %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <form method='post' class="form" style="display:absolute">
      {% csrf_token %}
      <div class="container">
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <br>
      <img class="mb-4" src="{% static "img/money.png" %}" alt="" width="100" height="90">
      <h1 class="h3 mb-3 font-weight-normal" style="font-family:Verdana">Login</h1>

      <label for="username" class="sr-only">Username</label>
      <input type="username" id="username" name="username" class="form-control" placeholder="Username">
      <br>
      <label for="password" class="sr-only">Password</label>
      <input type="password" id="password" name="password"class="form-control" placeholder="Password" required>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      <hr>
      {% comment %} <p class="mt-5 mb-3 text-muted">&copy; 2022-2023</p> {% endcomment %}
    </form>
    <a class="btn btn-primary pt-2 pl-1 pr-1 text-light" style="position:absolute;top:570px;width:200px"  href="{% url "register-user-finance" %}"> Register </a>
    </body>
</html>